#ifndef TOKEN
#define TOKEN(X)
#endif
#ifndef PUNCTUATOR
#define PUNCTUATOR(X,Y) TOKEN(X)
#endif
#ifndef KEYWORD
#define KEYWORD(X) TOKEN(KW_##X)
#endif

#ifndef PP_KEYWORD
#define PP_KEYWORD(X) TOKEN(PP_##X)
#endif

TOKEN(Unknown)
TOKEN(EoF)
TOKEN(NewLine)
TOKEN(EoD)
TOKEN(Comment)
TOKEN(Number)
TOKEN(Identifier)
TOKEN(String)

PUNCTUATOR(LeftSquare, "[")
PUNCTUATOR(RightSquare, "]")
PUNCTUATOR(LeftRound, "(")
PUNCTUATOR(RightRound, ")")
PUNCTUATOR(LeftBrace, "{")
PUNCTUATOR(RightBrace, "}")
PUNCTUATOR(Period, ".")
PUNCTUATOR(Ellipsis, "...")
PUNCTUATOR(Amp, "&")
PUNCTUATOR(AmpAmp, "&&")
PUNCTUATOR(AmpEqual, "&=")
PUNCTUATOR(Star, "*")
PUNCTUATOR(StarEqual, "*=")
PUNCTUATOR(Plus, "+")
PUNCTUATOR(PlusPlus, "++")
PUNCTUATOR(PlusEqual, "+=")
PUNCTUATOR(Minus, "-")
PUNCTUATOR(Arrow, "->")
PUNCTUATOR(MinusMinus, "--")
PUNCTUATOR(MinusEqual, "-=")
PUNCTUATOR(Tilde, "~")
PUNCTUATOR(Exclaim, "!")
PUNCTUATOR(ExclaimEqual, "!=")
PUNCTUATOR(Slash, "/")
PUNCTUATOR(SlashEqual, "/=")
PUNCTUATOR(Modulo, "%")
PUNCTUATOR(ModuloEqual, "%=")
PUNCTUATOR(Less, "<")
PUNCTUATOR(LessLess, "<<")
PUNCTUATOR(LessEqual, "<=")
PUNCTUATOR(LessLessEqual, "<<=")
PUNCTUATOR(Greater, ">")
PUNCTUATOR(GreaterGreater, ">>")
PUNCTUATOR(GreaterEqual, ">=")
PUNCTUATOR(GreaterGreatEqual, ">>=")
PUNCTUATOR(Caret, "^")
PUNCTUATOR(CaretEqual, "^=")
PUNCTUATOR(Pipe, "|")
PUNCTUATOR(PipePipe, "||")
PUNCTUATOR(PipeEqual, "|=")
PUNCTUATOR(Question, "?")
PUNCTUATOR(Colon, ":")
PUNCTUATOR(Semicolon, ";")
PUNCTUATOR(Equal, "=")
PUNCTUATOR(EqualEqual, "==")
PUNCTUATOR(Comma, ",")
PUNCTUATOR(Hash, "#")

KEYWORD(while)
KEYWORD(break)
KEYWORD(switch)
KEYWORD(case)
KEYWORD(for)
KEYWORD(goto)
KEYWORD(continue)
KEYWORD(do)
KEYWORD(if)
KEYWORD(else)
KEYWORD(return)
KEYWORD(enum)
KEYWORD(struct)
KEYWORD(const)
KEYWORD(typedef)
KEYWORD(bool)
KEYWORD(char)
KEYWORD(int)
KEYWORD(unsigned)
KEYWORD(long)
KEYWORD(float)
KEYWORD(double)
KEYWORD(void)

PP_KEYWORD(if)
PP_KEYWORD(else)
PP_KEYWORD(elif)
PP_KEYWORD(ifdef)
PP_KEYWORD(ifndef)
PP_KEYWORD(elifdef)
PP_KEYWORD(elifndef)
PP_KEYWORD(endif)
PP_KEYWORD(defined)
PP_KEYWORD(include)
PP_KEYWORD(define)
PP_KEYWORD(undef)

#undef PP_KEYWORD
#undef KEYWORD
#undef PUNCTUATOR
#undef TOKEN

